### ISSUE TITLE
On Click event

### ISSUE THREAD

**Issue by monikakalt** [rars/ngx-diff#38]
Is it possible to attach on click event? so that I'd be able to get line id and comment etc, something like github has.

**Comment by rars** [comment]
Yes, that's a good idea. I've added this in https://github.com/rars/ngx-diff/pull/41. Please let me know if you have any thoughts.

**Comment by rars** [comment]
Available in https://github.com/rars/ngx-diff/releases/tag/v3.0.0. Closing this issue. Please create another issue if there are any problems. Thanks.
