### ISSUE TITLE
Repeated DOM structure recreation warnings on Angular 18.2

### ISSUE THREAD

**Issue by kulitha** [rars/ngx-diff#93]
Repeated warnings about recreation of DOM structure are displayed on console whenever there's a diff update. I am using Angular 18.2. I tried using this on a new Angular project using the exact demo that was provided for this package, but the warnings still persist.

https://github.com/user-attachments/assets/ab012a37-d3df-44fa-8829-a4f992545e82

This is the warning that shows up in the console.

> NG0956: The configured tracking expression (track by identity) caused re-creation of the entire collection of size 7. This is an expensive operation requiring destruction and subsequent creation of DOM nodes, directives, components etc. Please review the "track expression" and make sure that it uniquely identifies items in a collection. Find more at https://angular.dev/errors/NG0956

[Relevant error link](https://angular.dev/errors/NG0956)

It seems like it could be fixed by changing the tracking expression (most likely for the line difference).

Any help would be much appreciated!

**Comment by rars** [comment]
Thanks @kulitha. I've released [v9.1.0](https://github.com/rars/ngx-diff/releases/tag/v9.1.0) to address this. Please try that and let me know if you still have any problems.

**Comment by kulitha** [comment]
Cheers! It's giving no warnings now and works perfectly. Thank you very much for the quick fix!
